package sv.ues.dominio;
// Generated 09-04-2019 10:41:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BitacoraLaboratorioChinche generated by hbm2java
 */
public class BitacoraLaboratorioChinche  implements java.io.Serializable {


     private int id;
     private Integer idPerfil;
     private Date fechaIngreso;
     private Date fechaTrabajo;
     private String departamento;
     private String municipio;
     private String canton;
     private String cacerio;
     private Date fechaColecta;
     private String nombreCientifico;
     private Integer numeroCasa;
     private String nombreJefeFamilia;
     private Boolean domiciliar;
     private Boolean peridomiciliar;
     private Boolean silvestre;

    public BitacoraLaboratorioChinche() {
    }

	
    public BitacoraLaboratorioChinche(int id) {
        this.id = id;
    }
    public BitacoraLaboratorioChinche(int id, Integer idPerfil, Date fechaIngreso, Date fechaTrabajo, String departamento, String municipio, String canton, String cacerio, Date fechaColecta, String nombreCientifico, Integer numeroCasa, String nombreJefeFamilia, Boolean domiciliar, Boolean peridomiciliar, Boolean silvestre) {
       this.id = id;
       this.idPerfil = idPerfil;
       this.fechaIngreso = fechaIngreso;
       this.fechaTrabajo = fechaTrabajo;
       this.departamento = departamento;
       this.municipio = municipio;
       this.canton = canton;
       this.cacerio = cacerio;
       this.fechaColecta = fechaColecta;
       this.nombreCientifico = nombreCientifico;
       this.numeroCasa = numeroCasa;
       this.nombreJefeFamilia = nombreJefeFamilia;
       this.domiciliar = domiciliar;
       this.peridomiciliar = peridomiciliar;
       this.silvestre = silvestre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaTrabajo() {
        return this.fechaTrabajo;
    }
    
    public void setFechaTrabajo(Date fechaTrabajo) {
        this.fechaTrabajo = fechaTrabajo;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getCacerio() {
        return this.cacerio;
    }
    
    public void setCacerio(String cacerio) {
        this.cacerio = cacerio;
    }
    public Date getFechaColecta() {
        return this.fechaColecta;
    }
    
    public void setFechaColecta(Date fechaColecta) {
        this.fechaColecta = fechaColecta;
    }
    public String getNombreCientifico() {
        return this.nombreCientifico;
    }
    
    public void setNombreCientifico(String nombreCientifico) {
        this.nombreCientifico = nombreCientifico;
    }
    public Integer getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(Integer numeroCasa) {
        this.numeroCasa = numeroCasa;
    }
    public String getNombreJefeFamilia() {
        return this.nombreJefeFamilia;
    }
    
    public void setNombreJefeFamilia(String nombreJefeFamilia) {
        this.nombreJefeFamilia = nombreJefeFamilia;
    }
    public Boolean getDomiciliar() {
        return this.domiciliar;
    }
    
    public void setDomiciliar(Boolean domiciliar) {
        this.domiciliar = domiciliar;
    }
    public Boolean getPeridomiciliar() {
        return this.peridomiciliar;
    }
    
    public void setPeridomiciliar(Boolean peridomiciliar) {
        this.peridomiciliar = peridomiciliar;
    }
    public Boolean getSilvestre() {
        return this.silvestre;
    }
    
    public void setSilvestre(Boolean silvestre) {
        this.silvestre = silvestre;
    }




}


