package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta  implements java.io.Serializable {


     private int idEncuesta;
     private BitacoraCampo bitacoraCampo;
     private String nomEncuesta;
     private Set preguntas = new HashSet(0);
     private Set encuestados = new HashSet(0);
     private Set encuestadors = new HashSet(0);

    public Encuesta() {
    }

	
    public Encuesta(int idEncuesta, BitacoraCampo bitacoraCampo) {
        this.idEncuesta = idEncuesta;
        this.bitacoraCampo = bitacoraCampo;
    }
    public Encuesta(int idEncuesta, BitacoraCampo bitacoraCampo, String nomEncuesta, Set preguntas, Set encuestados, Set encuestadors) {
       this.idEncuesta = idEncuesta;
       this.bitacoraCampo = bitacoraCampo;
       this.nomEncuesta = nomEncuesta;
       this.preguntas = preguntas;
       this.encuestados = encuestados;
       this.encuestadors = encuestadors;
    }
   
    public int getIdEncuesta() {
        return this.idEncuesta;
    }
    
    public void setIdEncuesta(int idEncuesta) {
        this.idEncuesta = idEncuesta;
    }
    public BitacoraCampo getBitacoraCampo() {
        return this.bitacoraCampo;
    }
    
    public void setBitacoraCampo(BitacoraCampo bitacoraCampo) {
        this.bitacoraCampo = bitacoraCampo;
    }
    public String getNomEncuesta() {
        return this.nomEncuesta;
    }
    
    public void setNomEncuesta(String nomEncuesta) {
        this.nomEncuesta = nomEncuesta;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getEncuestados() {
        return this.encuestados;
    }
    
    public void setEncuestados(Set encuestados) {
        this.encuestados = encuestados;
    }
    public Set getEncuestadors() {
        return this.encuestadors;
    }
    
    public void setEncuestadors(Set encuestadors) {
        this.encuestadors = encuestadors;
    }




}


