package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuestado generated by hbm2java
 */
public class Encuestado  implements java.io.Serializable {


     private int idEncuestado;
     private Encuesta encuesta;
     private Set personas = new HashSet(0);

    public Encuestado() {
    }

	
    public Encuestado(int idEncuestado, Encuesta encuesta) {
        this.idEncuestado = idEncuestado;
        this.encuesta = encuesta;
    }
    public Encuestado(int idEncuestado, Encuesta encuesta, Set personas) {
       this.idEncuestado = idEncuestado;
       this.encuesta = encuesta;
       this.personas = personas;
    }
   
    public int getIdEncuestado() {
        return this.idEncuestado;
    }
    
    public void setIdEncuestado(int idEncuestado) {
        this.idEncuestado = idEncuestado;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


