package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuestador generated by hbm2java
 */
public class Encuestador  implements java.io.Serializable {


     private int idEncuestador;
     private Encuesta encuesta;
     private Set personas = new HashSet(0);

    public Encuestador() {
    }

	
    public Encuestador(int idEncuestador, Encuesta encuesta) {
        this.idEncuestador = idEncuestador;
        this.encuesta = encuesta;
    }
    public Encuestador(int idEncuestador, Encuesta encuesta, Set personas) {
       this.idEncuestador = idEncuestador;
       this.encuesta = encuesta;
       this.personas = personas;
    }
   
    public int getIdEncuestador() {
        return this.idEncuestador;
    }
    
    public void setIdEncuestador(int idEncuestador) {
        this.idEncuestador = idEncuestador;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


