package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvVector generated by hbm2java
 */
public class InvVector  implements java.io.Serializable {


     private int idInvVector;
     private PerfilInv perfilInv;
     private Vector vector;
     private String tituloInv;
     private String descInvVector;
     private Set bitacoraCampos = new HashSet(0);
     private Set bitacoraLabs = new HashSet(0);

    public InvVector() {
    }

	
    public InvVector(int idInvVector, PerfilInv perfilInv, Vector vector) {
        this.idInvVector = idInvVector;
        this.perfilInv = perfilInv;
        this.vector = vector;
    }
    public InvVector(int idInvVector, PerfilInv perfilInv, Vector vector, String tituloInv, String descInvVector, Set bitacoraCampos, Set bitacoraLabs) {
       this.idInvVector = idInvVector;
       this.perfilInv = perfilInv;
       this.vector = vector;
       this.tituloInv = tituloInv;
       this.descInvVector = descInvVector;
       this.bitacoraCampos = bitacoraCampos;
       this.bitacoraLabs = bitacoraLabs;
    }
   
    public int getIdInvVector() {
        return this.idInvVector;
    }
    
    public void setIdInvVector(int idInvVector) {
        this.idInvVector = idInvVector;
    }
    public PerfilInv getPerfilInv() {
        return this.perfilInv;
    }
    
    public void setPerfilInv(PerfilInv perfilInv) {
        this.perfilInv = perfilInv;
    }
    public Vector getVector() {
        return this.vector;
    }
    
    public void setVector(Vector vector) {
        this.vector = vector;
    }
    public String getTituloInv() {
        return this.tituloInv;
    }
    
    public void setTituloInv(String tituloInv) {
        this.tituloInv = tituloInv;
    }
    public String getDescInvVector() {
        return this.descInvVector;
    }
    
    public void setDescInvVector(String descInvVector) {
        this.descInvVector = descInvVector;
    }
    public Set getBitacoraCampos() {
        return this.bitacoraCampos;
    }
    
    public void setBitacoraCampos(Set bitacoraCampos) {
        this.bitacoraCampos = bitacoraCampos;
    }
    public Set getBitacoraLabs() {
        return this.bitacoraLabs;
    }
    
    public void setBitacoraLabs(Set bitacoraLabs) {
        this.bitacoraLabs = bitacoraLabs;
    }




}


