package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int codLaboratorio;
     private Usuario usuario;
     private String nomLab;
     private String alias;
     private Set investigacions = new HashSet(0);

    public Laboratorio() {
    }

	
    public Laboratorio(int codLaboratorio, String nomLab) {
        this.codLaboratorio = codLaboratorio;
        this.nomLab = nomLab;
    }
    public Laboratorio(int codLaboratorio, Usuario usuario, String nomLab, String alias, Set investigacions) {
       this.codLaboratorio = codLaboratorio;
       this.usuario = usuario;
       this.nomLab = nomLab;
       this.alias = alias;
       this.investigacions = investigacions;
    }
   
    public int getCodLaboratorio() {
        return this.codLaboratorio;
    }
    
    public void setCodLaboratorio(int codLaboratorio) {
        this.codLaboratorio = codLaboratorio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomLab() {
        return this.nomLab;
    }
    
    public void setNomLab(String nomLab) {
        this.nomLab = nomLab;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public Set getInvestigacions() {
        return this.investigacions;
    }
    
    public void setInvestigacions(Set investigacions) {
        this.investigacions = investigacions;
    }




}


