package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codMunicipio;
     //private String depto;
     private Departamento departamento;
     private String nomMunicipio;
     private Set coloniaCantons = new HashSet(0);

    public Municipio() 
    {
    }

	
    public Municipio(String codMunicipio, Departamento departamento, String nomMunicipio/*, String depto*/) {
        this.codMunicipio = codMunicipio;
        this.departamento = departamento;
        this.nomMunicipio = nomMunicipio;
        //this.depto = depto;
    }
    public Municipio(String codMunicipio, Departamento departamento, String nomMunicipio, /*String depto,*/ Set coloniaCantons) {
       this.codMunicipio = codMunicipio;
       this.departamento = departamento;
       this.nomMunicipio = nomMunicipio;
       this.coloniaCantons = coloniaCantons;
       //this.depto = depto;
    }
   
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNomMunicipio() {
        return this.nomMunicipio;
    }
    
    public void setNomMunicipio(String nomMunicipio) {
        this.nomMunicipio = nomMunicipio;
    }
    public Set getColoniaCantons() {
        return this.coloniaCantons;
    }
    
    public void setColoniaCantons(Set coloniaCantons) {
        this.coloniaCantons = coloniaCantons;
    }

    /*public String getDepto() {
        return depto;
    }

    public void setDepto(String depto) {
        this.depto = depto;
    }*/




}


