package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Encuestado encuestado;
     private Encuestador encuestador;
     private Usuario usuario;
     private String nomPersona;
     private String apellPersona;
     private String correoPersona;
     private String telefonoPersona;
     private Integer edadPersona;

    public Persona() {
    }

	
    public Persona(int idPersona, String nomPersona) {
        this.idPersona = idPersona;
        this.nomPersona = nomPersona;
    }
    public Persona(int idPersona, Encuestado encuestado, Encuestador encuestador, Usuario usuario, String nomPersona, String apellPersona, String correoPersona, String telefonoPersona, Integer edadPersona) {
       this.idPersona = idPersona;
       this.encuestado = encuestado;
       this.encuestador = encuestador;
       this.usuario = usuario;
       this.nomPersona = nomPersona;
       this.apellPersona = apellPersona;
       this.correoPersona = correoPersona;
       this.telefonoPersona = telefonoPersona;
       this.edadPersona = edadPersona;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Encuestado getEncuestado() {
        return this.encuestado;
    }
    
    public void setEncuestado(Encuestado encuestado) {
        this.encuestado = encuestado;
    }
    public Encuestador getEncuestador() {
        return this.encuestador;
    }
    
    public void setEncuestador(Encuestador encuestador) {
        this.encuestador = encuestador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomPersona() {
        return this.nomPersona;
    }
    
    public void setNomPersona(String nomPersona) {
        this.nomPersona = nomPersona;
    }
    public String getApellPersona() {
        return this.apellPersona;
    }
    
    public void setApellPersona(String apellPersona) {
        this.apellPersona = apellPersona;
    }
    public String getCorreoPersona() {
        return this.correoPersona;
    }
    
    public void setCorreoPersona(String correoPersona) {
        this.correoPersona = correoPersona;
    }
    public String getTelefonoPersona() {
        return this.telefonoPersona;
    }
    
    public void setTelefonoPersona(String telefonoPersona) {
        this.telefonoPersona = telefonoPersona;
    }
    public Integer getEdadPersona() {
        return this.edadPersona;
    }
    
    public void setEdadPersona(Integer edadPersona) {
        this.edadPersona = edadPersona;
    }




}


