package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Preservante generated by hbm2java
 */
public class Preservante  implements java.io.Serializable {


     private int idPreservante;
     private String nomPreservante;
     private String descPreservante;
     private Set lotes = new HashSet(0);

    public Preservante() {
    }

	
    public Preservante(int idPreservante, String nomPreservante, String descPreservante) {
        this.idPreservante = idPreservante;
        this.nomPreservante = nomPreservante;
        this.descPreservante = descPreservante;
    }
    public Preservante(int idPreservante, String nomPreservante, String descPreservante, Set lotes) {
       this.idPreservante = idPreservante;
       this.nomPreservante = nomPreservante;
       this.descPreservante = descPreservante;
       this.lotes = lotes;
    }
   
    public int getIdPreservante() {
        return this.idPreservante;
    }
    
    public void setIdPreservante(int idPreservante) {
        this.idPreservante = idPreservante;
    }
    public String getNomPreservante() {
        return this.nomPreservante;
    }
    
    public void setNomPreservante(String nomPreservante) {
        this.nomPreservante = nomPreservante;
    }
    public String getDescPreservante() {
        return this.descPreservante;
    }
    
    public void setDescPreservante(String descPreservante) {
        this.descPreservante = descPreservante;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }




}


