package sv.ues.dominio;
// Generated 06-15-2019 03:20:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String descripcion;
     private Set usuarioRols = new HashSet(0);

    public Rol() {
    }

	
    public Rol(long id) {
        this.id = id;
    }
    public Rol(long id, String nombre, String descripcion, Set usuarioRols) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuarioRols = usuarioRols;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


