package sv.ues.dominio;
// Generated 06-15-2019 03:20:57 AM by Hibernate Tools 4.3.1



/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol  implements java.io.Serializable {


     private long id;
     private Rol rol;
     private Usuario usuario;

    public UsuarioRol() {
    }

	
    public UsuarioRol(long id) {
        this.id = id;
    }
    public UsuarioRol(long id, Rol rol, Usuario usuario) {
       this.id = id;
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


