package sv.ues.dominio;
// Generated 06-15-2019 03:20:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long id;
     private EstadoUsuario estadoUsuario;
     private TipoUsuario tipoUsuario;
     private String nombre;
     private String contrasena;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set personas = new HashSet(0);
     private Set usuarioRols = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long id) {
        this.id = id;
    }
    public Usuario(long id, EstadoUsuario estadoUsuario, TipoUsuario tipoUsuario, String nombre, String contrasena, Date fechaCreacion, Date fechaModificacion, Set personas, Set usuarioRols) {
       this.id = id;
       this.estadoUsuario = estadoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.personas = personas;
       this.usuarioRols = usuarioRols;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public EstadoUsuario getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(EstadoUsuario estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }
    public Set getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


